### ISSUE TITLE
gradient alpha channel ignored

### ISSUE THREAD

**Issue by billzez** [jpbruyere/vkvg#103]
It seems the alpha channel in gradients is ignored.  For example, if I create a linear gradient with two identical color stops (r=1, g=0, b=0, a=0.5), I would expect the behavior to be the same as set_source_rgba(1,0,0,0.5), but instead I get solid red with no blending.

**Comment by jpbruyere** [comment]
I add a new test for gradient alpha (commit=c5b5689, test file=tests/gradient.c, test num=0) and got the expected blending. What's your result with this test?

**Comment by billzez** [comment]
I can confirm your test works.  Perhaps I set up my vulkan device incorrectly.  Closing...
