### ISSUE TITLE
Segfaults in surface test

### ISSUE THREAD

**Issue by Rubo3** [jpbruyere/vkvg#106]
When I run the test `surface` in release mode, it always segfaults, sometimes with `malloc_consolidate(): unaligned fastbin chunk detected`, or `free(): double free detected in tcache 2`. While in debug mode I also get `corrupted double-linked list`, `munmap_chunk(): invalid pointer`, `free(): invalid pointer`, `double free or corruption (!prev)` or `malloc(): unsorted double linked list corrupted`.

**Comment by jpbruyere** [comment]
That's an easy bug to find. Do you want me to correct it, or do I let you find it, that's in tests/surface.c
