### ISSUE TITLE
M_PI undeclared

### ISSUE THREAD

**Issue by kcleal** [jpbruyere/vkvg#126]
Hi,

I had this issue when running build::
    
    error: ‘M_PI’ undeclared (first use in this function); did you mean ‘M_PIF’?
      752 |                 vkvg_arc(ctx, x + r, y + r, r, (float)M_PI, (float)-M_PI_2);
          |                                                       ^~~~
          |                                                       M_PIF

And also::

    error: ‘M_PI_2’ undeclared (first use in this function); did you mean ‘M_PIF’?
      752 |                 vkvg_arc(ctx, x + r, y + r, r, (float)M_PI, (float)-M_PI_2);
          |                                                                     ^~~~~~
          |                                                                     M_PIF
    
Probably just needs to be defined...

**Comment by jpbruyere** [comment]
I've disabled c extensions in main CMake after a request for another c compiler, I've not noticed it removed also M_PI, my local cmake having c exts enabled..., thanks for your report. The easiest solution is to set 'SET(CMAKE_C_EXTENSIONS on)' in the main CMakeLists.txt in the root directory. I'll try to fix this in my next push on master.

**Comment by jpbruyere** [comment]
I've enabled c extensions by default, threading need more work without it...
