### ISSUE TITLE
tests/bezier screen not clear on each frame

### ISSUE THREAD

**Issue by locriacyber** [jpbruyere/vkvg#127]
![image](https://user-images.githubusercontent.com/74560659/205185828-76b34687-bddb-411d-8e8f-1f5388584492.png)

**Comment by jpbruyere** [comment]
I would need some clue to be able to reproduce. I've never get such output. Please give your platform, drivers, hardware, and so on....

**Comment by locriacyber** [comment]
platform: Linux
drivers: OpenGL?

the other examples like `tests/arc` work well, only this particular example is buggy

**Comment by jpbruyere** [comment]
I need details on you platform, drivers and hardware. Without that, I can't help you. That's maybe a missing required feature or extension, but most probably, a driver bug.
