### ISSUE TITLE
Cannot build tests on linux with static GLFW

### ISSUE THREAD

**Issue by locriacyber** [jpbruyere/vkvg#128]
I installed GLFW3 from source, at it installs as static library by default.

How to link it properly:

- use `pkgconf --static --libs glfw3`
- add `-lX11` after each `-lm` in `build.ninja` (better to do it in CMakeLists.txt)

**Comment by jpbruyere** [comment]
static glfw should already have platform libs linkage. If you compile glfw from source, maybe try add_directory(glfw_src_path) in cmake, that's the preferred way to include it to client project.

**Comment by locriacyber** [comment]
CMake generated the build files for Njna.
`ninja -v` invokes `gcc`, which is not linking with `-lX11`.

**Comment by jpbruyere** [comment]
I've tested linking against a static glfw, with makefiles and ninja, and I got no problem. I'm on Debian testing, maybe give details on your platform, if I have time, I will test.
