### ISSUE TITLE
Multi-window support?

### ISSUE THREAD

**Issue by 173619070** [jpbruyere/vkvg#129]
i want to use it in multiple window,so what can i do? should i create another VkSurfaceKHR object ?what about another resource?

**Comment by jpbruyere** [comment]
what other resource? another VkSurfaceKHR sounds good.

**Comment by 173619070** [comment]
> what other resource? another VkSurfaceKHR sounds good, if you are using the same physical device and graphic queue, a single VkvgDevice could output to vulkan image from both. Vkvg is basically to draw on vulkan texture, it does not handle the windowing system, you need some kind of window manager (like glfw) for that. If you make a nice example with glfw and multiple window, I can add it to the repo.

you didn't understand what i said ，what I mean is that  in multi-window mode those resources are shared by windows, and those resources are exclusive to windows，are you distinguishing in your code，I think a better way is to develop based on windows，common 2D applications have multiple windows

**Comment by jpbruyere** [comment]
I'm sorry but my time is a bit short, feel free to come back to me with concrete examples and materials.
