### ISSUE TITLE
missing stbi

### ISSUE THREAD

**Issue by vbextreme** [jpbruyere/vkvg#13]
for build vkvg need install stb, on fedora
```
sudo dnf install stbi-devel
```
and edit CMakeLists.txt on line 7
```
SET(CMAKE_EXE_LINKER_FLAGS "-lm -lstbi")
```

**Comment by jpbruyere** [comment]
I have added "stb_image.h" to the source tree (it was in my system include dir), thanks for the report.
Its a single header library, so no need to change linker flags.

**Comment by vbextreme** [comment]
make fail without linking a lib

**Comment by jpbruyere** [comment]
Try to recompile master after a "git pull" to get **stb_image.h** in the **src** folder, and recompile without cmake change. It should be fine.

**Comment by vbextreme** [comment]
ok, build ok.
I have problem with my driver gpu
```
INTEL-MESA: warning: Ivy Bridge Vulkan support is incomplete
fish: './vkvg_test' terminated by signal SIGSEGV (Address boundary error)
```
Wait Feodra 28

**Comment by jpbruyere** [comment]
Vulkan drivers are in early development state too, I have also several issues with incomplete drivers, and I have 2 cards, none is fully functional. 
I use latest development version of Mesa and libdrm, which provides latest fixes.

```
git clone https://anongit.freedesktop.org/git/mesa/mesa.git
git clone http://anongit.freedesktop.org/git/mesa/drm.git
```

I compile mesa with the following options:
```
'--enable-gles1' '--enable-gles2' '--enable-glx-tls' '--with-vulkan-drivers=intel,radeon' '--enable-gbm' '--enable-texture-float' '--with-dri-drivers=radeon,i965,' '--with-gallium-drivers=radeonsi,i915,swrast,virgl' '--with-platforms=x11,drm,surfaceless,wayland' '--with-dri-driver=/usr/local/lib/dri'
```
also be sure to have [latest libvulkan from lunarg](https://www.lunarg.com/vulkan-sdk/)

**Comment by vbextreme** [comment]
thank you.
Waits next weeks with fedora28.
Mix manual build software with default software installed over package manager isn't a best way
