### ISSUE TITLE
Vulkan validator prints error on fragment compilation (vkCreateShaderModule)

### ISSUE THREAD

**Issue by ar-visions** [jpbruyere/vkvg#139]
line 300 in vkvg_device_internal.c:

```
	VkShaderModuleCreateInfo createInfo = { .sType = VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO,
											.pCode = (uint32_t*)vkvg_main_vert_spv,
											.codeSize = vkvg_main_vert_spv_len };
	VK_CHECK_RESULT(vkCreateShaderModule(dev->vkDev, &createInfo, NULL, &modVert));
#if defined(VKVG_LCD_FONT_FILTER) && defined(FT_CONFIG_OPTION_SUBPIXEL_RENDERING)
	createInfo.pCode = (uint32_t*)vkvg_main_lcd_frag_spv;
	createInfo.codeSize = vkvg_main_lcd_frag_spv_len;
#else
	createInfo.pCode = (uint32_t*)vkvg_main_frag_spv;
	createInfo.codeSize = vkvg_main_frag_spv_len;
#endif
	VK_CHECK_RESULT(vkCreateShaderModule(dev->vkDev, &createInfo, NULL, &modFrag)); /// errors.

```
This is inside the _device_setupPipelines(vkvg_device) function

Validator error:
```
validation layer: Validation Error: [ VUID-VkShaderModuleCreateInfo-pCode-01379 ] Object 0: handle = 0x555557288900, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x2a1bf17f | SPIR-V module not valid: Structure id 90 decorated as Block for variable in Uniform storage class must follow relaxed uniform buffer layout rules: member 1 contains an array with stride 4 not satisfying alignment to 16
  %_uboGrad = OpTypeStruct %_arr_v4float_uint_16 %_arr_float_uint_16 %_arr_v4float_uint_2 %uint
```

I suppose for me this means find the fragment & vertex sources and compile them with my own glslc.  I was reasonably certain that VkVG did this during its build process, though?  At any rate I am having this error and am trying to get it going..

I really appreciate your work on this!

**Comment by ar-visions** [comment]
```
#if defined(VKVG_LCD_FONT_FILTER) && defined(FT_CONFIG_OPTION_SUBPIXEL_RENDERING)
	createInfo.pCode = (uint32_t*)vkvg_main_lcd_frag_spv;
	createInfo.codeSize = vkvg_main_lcd_frag_spv_len;
#else
	createInfo.pCode = (uint32_t*)vkvg_main_frag_spv; /// <- this specific one is being used
	createInfo.codeSize = vkvg_main_frag_spv_len;
#endif
```

**Comment by ar-visions** [comment]
I pulled in those changes and still seem to get the error.  I did rebuild but I'll update my json to pull in the master so all changes are applied since that spv change.

**Comment by ar-visions** [comment]
A change I had to make in order to get this going this far was an upgrade to VMA version as I use it already in a specific version that is greater than the one used here.   So, I had to pass the instance in vkvg_device.c as well as vh_device.c:
```
#ifdef VKH_USE_VMA
	VmaAllocatorCreateInfo allocatorInfo = {
		.physicalDevice = phy,
		.device = vkDev,
                .instance = inst
	};
	vmaCreateAllocator(&allocatorInfo, &dev->allocator);
```

**Comment by ar-visions** [comment]
Undefining VKVG_ENABLE_VK_SCALAR_BLOCK_LAYOUT lets it pass the validator.  I am onto another issue now.

device internal @ ~358: (last vkCreateGraphicsPipelines call in function: _device_setupPipelines)
VK_CHECK_RESULT(vkCreateGraphicsPipelines(dev->vkDev, dev->pipelineCache, 1, &pipelineCreateInfo, NULL, &dev->pipe_CLEAR));

```
Validation Error: [ VUID-VkPipelineColorBlendStateCreateInfo-logicOpEnable-00606 ] Object 0: handle = 0x5555572889a0, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x234f6296 | vkCreateGraphicsPipelines() pCreateInfo[0]: If logic operations feature not enabled, logicOpEnable must be VK_FALSE. The Vulkan spec states: If the logicOp feature is not enabled, logicOpEnable must be VK_FALSE (https://vulkan.lunarg.com/doc/view/1.3.250.0/linux/1.3-extensions/vkspec.html#VUID-VkPipelineColorBlendStateCreateInfo-logicOpEnable-00606)
```

**Comment by ar-visions** [comment]
Important to note that VKVG_ENABLE_VK_SCALAR_BLOCK_LAYOUT should be OFF for current version of vulkan validator not to error.  Perhaps it could be default or we fix by padding the float[16]

**Comment by jpbruyere** [comment]
> The above was due to my mistake at Vulkan Device creation. I needed to add the following. 'aa' is unlikely to ever be false as I assume that would break vkvg's pipeline requirements
> 
> VkPhysicalDeviceFeatures features { **.logicOp = VK_TRUE**, .samplerAnisotropy = aa ? VK_TRUE : VK_FALSE };

You should call 'vkvg_get_device_requirements' to populate the 'VkPhysicalDeviceFeatures' struct.



> Important to note that VKVG_ENABLE_VK_SCALAR_BLOCK_LAYOUT should be OFF (not defined) for current version of vulkan validator not to error. Perhaps it could be default or we fix by padding the float[16]

What is you vulkan version?  What is your platform, driver and gpu? SCALAR block layout could be unsupported by driver, vulkan side should be ok.

**Comment by jpbruyere** [comment]
> I was reasonably certain that VkVG did this during its build process, though? At any rate I am having this error and am trying to get it going..
If 'glslc' and 'xxd' binaries are found by cmake, shaders should be compiled by the cmake build. I've stored in the git tree a default version of pre-compiled spir-v shaders, but macros are forwarded to glslc compile command depending on cmake options. So, if you use the pre-compiled shaders from the git tree, cmake options and spir-v macros may be out of sync.
We could maybe set the most secured options if cmake failed detecting glslc or xxd, and ensure pre-compiled shaders have the same options compiled.
