### ISSUE TITLE
Cant run test with VK_IMAGE_TILING_LINEAR images.

### ISSUE THREAD

**Issue by lieff** [jpbruyere/vkvg#15]
```
IMAGE(ERROR / SPEC): object: 0x0 type: 0 msgNum: 165676968 - vkCreateImage: usage bit VK_IMAGE_USAGE_COLOR_ATTACHMENT is not supported for format VK_FORMAT_B8G8R8A8_UNORM with tiling VK_IMAGE_TILING_LINEAR. The spec valid usage text states 'If tiling is VK_IMAGE_TILING_LINEAR, and VkFormatProperties::linearTilingFeatures (as returned by vkGetPhysicalDeviceFormatProperties with the same value of format) does not include VK_FORMAT_FEATURE_COLOR_ATTACHMENT_BIT, usage must not contain VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-VkImageCreateInfo-tiling-00980)
IMAGE(ERROR): object: 0x0 type: 0 location: 677 msg_code: 165676968: Object: 0x0 | vkCreateImage: usage bit VK_IMAGE_USAGE_COLOR_ATTACHMENT is not supported for format VK_FORMAT_B8G8R8A8_UNORM with tiling VK_IMAGE_TILING_LINEAR. The spec valid usage text states 'If tiling is VK_IMAGE_TILING_LINEAR, and VkFormatProperties::linearTilingFeatures (as returned by vkGetPhysicalDeviceFormatProperties with the same value of format) does not include VK_FORMAT_FEATURE_COLOR_ATTACHMENT_BIT, usage must not contain VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-VkImageCreateInfo-tiling-00980)
IMAGE(ERROR / SPEC): object: 0x0 type: 0 msgNum: 165676888 - vkCreateImage: The combination of format, type, tiling, usage and flags supplied in the VkImageCreateInfo struct is reported by vkGetPhysicalDeviceImageFormatProperties() as unsupported. The spec valid usage text states 'The combination of format, imageType, tiling, usage, and flags must be supported, as indicated by a VK_SUCCESS return value from vkGetPhysicalDeviceImageFormatProperties invoked with the same values passed to the corresponding parameters.' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-VkImageCreateInfo-format-00940)
IMAGE(ERROR): object: 0x0 type: 0 location: 708 msg_code: 165676888: Object: 0x0 | vkCreateImage: The combination of format, type, tiling, usage and flags supplied in the VkImageCreateInfo struct is reported by vkGetPhysicalDeviceImageFormatProperties() as unsupported. The spec valid usage text states 'The combination of format, imageType, tiling, usage, and flags must be supported, as indicated by a VK_SUCCESS return value from vkGetPhysicalDeviceImageFormatProperties invoked with the same values passed to the corresponding parameters.' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-VkImageCreateInfo-format-00940)
vkvg_test: vkh_image.c:57: _vkh_image_create: Assertion `res == VK_SUCCESS' failed.
```

If I change VK_IMAGE_TILING_LINEAR->VK_IMAGE_TILING_OPTIMAL then vkvg_test runs, but still with validation errors: 

```
DS(ERROR / SPEC): object: 0x1f00 type: 23 msgNum: 61 - Descriptor set 0x1f00 encountered the following validation error at vkCmdDrawIndexed() time: Descriptor in bindi
ng #0 at global descriptor index 0 is being used in draw but has not been updated.
```

**Comment by jpbruyere** [comment]
Depending on your hardware, this combination doesn't seem to be accepted. I can't remember why I let the tiling of the single sampled backend texture to linear, I set it to optimal and will see if it does not hurt.
The validation error comes from the source uniform (Sampler2D) used in the main shader which is used only for surface painting, when painting with solid color or gradient, it's not binded. The options to solve this is either bind a dummy texture when source is unused or duplicate the main shader (but it would duplicate also the pipelines).
Thanks for your report.

**Comment by lieff** [comment]
Hardware: Nvidia GTX 980, driver v390

**Comment by jpbruyere** [comment]
After several test with Optimal tiling for the single sample backend img, the conclusion is that there is some other reasons for me to have kept it in linear tiling. (In fact, I had already implemented loading and saving with staging buffers)
Copy operations with optimal tiling has some constrains tied to what's called image transfer granularity, that cause on screen output and saving to png to fail with certain surface dimentions. Using square sizing and power of 2 dimensions ensure success, but vkvg should be able to handle random sizing for surfaces.
I've tried also to test `vkGetPhysicalDeviceImageFormatProperties2` but it sigsev, I'll test with other drivers and gpu.
What is your OS? is it windows? Did you get something on screen when running test? if not, try engine and surface size to 512x512 and Optimal tiling.
I'll try to test what could be achieve with transfer granularity...

**Comment by lieff** [comment]
Im using Ubuntu 18.04. With VK_IMAGE_TILING_OPTIMAL I get following:
![screenshot from 2018-08-03 19-53-02](https://user-images.githubusercontent.com/10080078/43655327-f52ee8de-9756-11e8-849c-7de438011500.png)

**Comment by tokyovigilante** [comment]
Using `VK_IMAGE_TILING_LINEAR` fails on MoltenVK on macOS too. Works fine with `VK_IMAGE_TILING_OPTIMAL `. Is there any reason not to use `VK_IMAGE_TILING_OPTIMAL` always?

**Comment by jpbruyere** [comment]
I should add a complete supported image format check at device creation. It depends on hardware and driver implementation.
VK_IMAGE_TILING_OPTIMAL add sometimes some texture size constraints, and vkvg surface should be able to handle any size.

**Comment by tokyovigilante** [comment]
That might be a better approach, I note Nvidia seems to favour
VK_IMAGE_TILING_OPTIMAL too.
https://devtalk.nvidia.com/default/topic/926085/vulkan/texture-memory-management/
Thanks very much for your work on this, great library! By far the best
solution I've found for easy 2D drawing with Vulkan.

On Sun, 6 Jan 2019, at 8:59 PM, j-p wrote:
> 


> I should add a complete supported image format check at device
> creation. It depends on hardware and driver implementation.>  VK_IMAGE_TILING_OPTIMAL add sometimes some texture size constraints,
>  and vkvg surface should be able to handle any size.> 


> — You are receiving this because you commented. Reply to this email
> directly, view it on GitHub[1], or mute the thread[2].

Links:

  1. https://github.com/jpbruyere/vkvg/issues/15#issuecomment-451729362

**Comment by jpbruyere** [comment]
Dynamic selection of tiling has been implemented, don't hesitate to give feedback.
