### ISSUE TITLE
Logo idea

### ISSUE THREAD

**Issue by MarcusJohnson91** [jpbruyere/vkvg#2]
VKVG is Vectors in Vulkan, right?

So why not have the icon be a volcano, with beziér  curve handles on a line and it's pulling at a line as it's expanding like you're making it erupt.

I feel like that could be an awesome logo ngl.

**Comment by jpbruyere** [comment]
why not, but try to give me a draft prototype, I can't visualize your idea, but it sounds good.

**Comment by bumblebritches57** [comment]
I'm going to be very busy for the next week, after that I can do a quick drawing of what I'm trying to describe for you.
