### ISSUE TITLE
Validation give errors with image format not being in presentable format

### ISSUE THREAD

**Issue by felipealmeida** [jpbruyere/vkvg#24]
Output repets last error several times:

WRN:  [ UNASSIGNED-CoreValidation-DrawState-InvalidRenderpass ] Object: VK_NULL_HANDLE (Type = 0) | Render pass has an attachment with loadOp == V
K_ATTACHMENT_LOAD_OP_LOAD and initialLayout == VK_IMAGE_LAYOUT_UNDEFINED.  This is probably not what you intended.  Consider using VK_ATTACHMENT_L
OAD_OP_DONT_CARE instead if the image truely is undefined at the start of the render pass.                                                       
WRN:  [ UNASSIGNED-CoreValidation-DrawState-InvalidRenderpass ] Object: VK_NULL_HANDLE (Type = 0) | Render pass has an attachment with stencilLoad
Op == VK_ATTACHMENT_LOAD_OP_LOAD and initialLayout == VK_IMAGE_LAYOUT_UNDEFINED.  This is probably not what you intended.  Consider using VK_ATTAC
HMENT_LOAD_OP_DONT_CARE instead if the image truely is undefined at the start of the render pass.                                                
WRN:  [ UNASSIGNED-CoreValidation-DrawState-InvalidRenderpass ] Object: VK_NULL_HANDLE (Type = 0) | Render pass has an attachment with loadOp == V
K_ATTACHMENT_LOAD_OP_LOAD and initialLayout == VK_IMAGE_LAYOUT_UNDEFINED.  This is probably not what you intended.  Consider using VK_ATTACHMENT_L
OAD_OP_DONT_CARE instead if the image truely is undefined at the start of the render pass.                                                       
DBG: While debugging through RenderDoc, debug output through validation layers is suppressed.
To show debug output look at the 'DebugOutputMute' capture option in RenderDoc's API, but be aware of false positives from the validation layers.
ERR:  [ VUID-vkAcquireNextImageKHR-semaphore-01780 ] Object: 0x557f21c34aa0 (Type = 3) | vkAcquireNextImageKHR: Semaphore and fence cannot both be
 VK_NULL_HANDLE. There would be no way to determine the completion of this operation. The Vulkan spec states: semaphore and fence must not both be
 equal to VK_NULL_HANDLE (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-vkAcquireNextImageKHR-semaphore-01780
)                                                                                                                                                
ERR:  [ VUID-VkPresentInfoKHR-pImageIndices-01296 ] Object: 0x557f21c9cac0 (Type = 4) | Images passed to present must be in layout VK_IMAGE_LAYOUT
_PRESENT_SRC_KHR or VK_IMAGE_LAYOUT_SHARED_PRESENT_KHR but is in VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL. The Vulkan spec states: Each element of
 pImageIndices must be the index of a presentable image acquired from the swapchain specified by the corresponding element of the pSwapchains arra
y, and the presented image subresource must be in the VK_IMAGE_LAYOUT_PRESENT_SRC_KHR layout at the time the operation is executed on a VkDevice (
https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkPresentInfoKHR-pImageIndices-01296)                         
ERR:  [ VUID-vkAcquireNextImageKHR-semaphore-01780 ] Object: 0x557f21c34aa0 (Type = 3) | vkAcquireNextImageKHR: Semaphore and fence cannot both be
 VK_NULL_HANDLE. There would be no way to determine the completion of this operation. The Vulkan spec states: semaphore and fence must not both be
 equal to VK_NULL_HANDLE (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-vkAcquireNextImageKHR-semaphore-01780
)                                                                                                                                                
ERR:  [ VUID-VkPresentInfoKHR-pImageIndices-01296 ] Object: 0x557f21c9cac0 (Type = 4) | Images passed to present must be in layout VK_IMAGE_LAYOUT
_PRESENT_SRC_KHR or VK_IMAGE_LAYOUT_SHARED_PRESENT_KHR but is in VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL. The Vulkan spec states: Each element of
 pImageIndices must be the index of a presentable image acquired from the swapchain specified by the corresponding element of the pSwapchains arra
y, and the presented image subresource must be in the VK_IMAGE_LAYOUT_PRESENT_SRC_KHR layout at the time the operation is executed on a VkDevice (
https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkPresentInfoKHR-pImageIndices-01296)                         
ERR:  [ VUID-vkAcquireNextImageKHR-semaphore-01780 ] Object: 0x557f21c34aa0 (Type = 3) | vkAcquireNextImageKHR: Semaphore and fence cannot both be
 VK_NULL_HANDLE. There would be no way to determine the completion of this operation. The Vulkan spec states: semaphore and fence must not both be
 equal to VK_NULL_HANDLE (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-vkAcquireNextImageKHR-semaphore-01780
)

**Comment by jpbruyere** [comment]
It's the main surface image, the loadop is LOAD to keep content between context creation/destruction. Load seems to need precise layout instead of unknown. I'm wandering about automatic layout transition in render pass depending on init/final and subpass layout. Next commit will have the fix (in vkvg_device_internal.c: VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL for init layout of first attachment, but I'm not sure if I have to transition by myself between present/color_attachment, I'll have to handle more tests. Thanks for your report.
