### ISSUE TITLE
Samples Questions

### ISSUE THREAD

**Issue by Joaopmoliveira** [jpbruyere/vkvg#33]
Question: In the samples you define the graphics and the presentation queue as the same queue. Is it possible that this becomes a bottleneck for the measurements?

**Comment by Joaopmoliveira** [comment]
And you use the following command to synchronize the application with the GPU:
```banch
vkDeviceWaitIdle()
```
Is there a reason for not using fences?

**Comment by jpbruyere** [comment]
You are right, waiting on device idle is overkill, I can use a draw fence. for the queues, I'll update the rendering loop in the next push on master.
I think lots of middle-market cards has only one graphic queue that support presentation. Also presentation should be transfer operations in the hardware, it should be ok for processing cycles.
We have to sync with final image from surface, it's availability is guaranteed on context destruction. We may test a triple buffering (vkvg_surface_image->image->presentation_image.) now it's (vkvg_surf_image->presentation_image). We may optimize the queue selection to fit to all hardware configurations.
I'm also thinking of a surface fence.

**Comment by Joaopmoliveira** [comment]
I have a sample tutorial where I can test things but the memory barrier to copy the drawing surface is crashing the application... I will send you the sample afterwards.

**Comment by Joaopmoliveira** [comment]
If I can finish these I might understand the code well enough to contribute to source!

**Comment by Joaopmoliveira** [comment]
This file contains the example I built which tries to remove the need for vkh. The function linkVulkanWithDrawingSurface is throwing an error at runtime at the moment. To compile the code we need a C++ 17 compatible compiler. If you don't like the fact that it uses C++ I can try to translate it into C but the simplicity goes a bit out the window.
[testing.txt](https://github.com/jpbruyere/vkvg/files/4604142/testing.txt)

**Comment by Joaopmoliveira** [comment]
The code does not have any comments at the moment because it still does not work!

**Comment by jpbruyere** [comment]
after a quick run, validation report pNext invalid value in Create structs. This means that you structure are not well initialized, and content of fields you don't use, are not zeroed.

**Comment by Joaopmoliveira** [comment]
I will try to correct that along the code. But I noticed that once create my swapChain and check the property VK_FORMAT_FEATURE_BLIT_SRC_BIT of the physical device it fails. So I need to query for a physical device which supports this property?

**Comment by jpbruyere** [comment]
yes, if you use blitting for copying vkvg image to swapchain image, but you may render with a full screen texture pipeline and the vkvg image as attachment if you don't have blit source/dest. Also you have to say when you create your swapchain, which usage you plan for its images, if you don't have blit_dst in the swapchain create info fields, it will fail even if that format support blitting.

**Comment by Joaopmoliveira** [comment]
I have it working... I forgot to add the context creation function... But I have the file now working. How detailed do you want my description to be? Something like this? 
[LunarSamples](https://vulkan.lunarg.com/doc/sdk/1.2.135.0/windows/tutorial/html/index.html)
The code which I will try to explain is here: 
[vkvg_code.txt](https://github.com/jpbruyere/vkvg/files/4606197/vkvg_code.txt)

**Comment by jpbruyere** [comment]
Try maybe to avoid too deep explanation on vulkan details, and redirect to other dedicated tutorials. For vkvg, explain from you point of view, trying to point what you needed to understand to complete this sample, be creative and do what you think is best.

**Comment by Joaopmoliveira** [comment]
Ok, working on it today. Can you give me permission to submit files to the repository?

**Comment by jpbruyere** [comment]
No, you have your fork and you propose pull request. That's the normal procedure. If this account was a company, it would be ok to share permissions, but on my personal account, there's no way to have me give write permissions to it, even to close collaborators or friends.

**Comment by jpbruyere** [comment]
Also note that vkvg is the result of about 10-15 years of work and learning.

**Comment by Joaopmoliveira** [comment]
Got it!
