### ISSUE TITLE
Unable to make on Windows 10. Can't find FreeType

### ISSUE THREAD

**Issue by btipton-ds** [jpbruyere/vkvg#36]
I keep getting this message.

CMake Error at C:/Program Files/CMake/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Freetype (missing: FREETYPE_LIBRARY FREETYPE_INCLUDE_DIRS)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files/CMake/share/cmake-3.13/Modules/FindFreetype.cmake:156 (find_package_handle_standard_args)
  CMakeLists.txt:74 (FIND_PACKAGE)

I've tried installing FreeType two different ways. Once via the detailed Windows Instructions and directly from the FreeType download.

I'm building for x64.

I've tried manually doing
set FREETYPE_INCLUDE_DIRS="\Program Files (x86)\GnuWin32\include"
set FREETYPE_LIBRARY="\Program Files (x86)\GnuWin32\lib"

This had no effect.

**Comment by jpbruyere** [comment]
FREETYPE_LIBRARY must contain the full share library file path, not the directory (../../freetype.dll). The easyest way to get vkvg running on windows is to use vcpkg, double check that you're using the CMAKE_TOOLCHAIN_FILE pointing to %vcpkg_root%\scripts\buildsystems\vcpkg.cmake. Also on windows I've issue the 'vcpkg integrate install' command, I'm not sure it was necessary, but try it if you didn't build with it.

**Comment by btipton-ds** [comment]
I'm already using vcpkg, per the instructions.

I'm not very familiar with details of CMake on windows. Are FREETYPE_LIBRARY and CMAKE_TOOLCHAIN_FILE windows environment variables? Or are they defined somewhere in the make files?
I've set FREETYPE_LIBRARY = C:\Program Files (x86)\GnuWin32\lib
Which is the directory which contains all the libs and dlls
I've set the include path to the include directory as well.
But I've set them as environment variables.

Should this be done in a normal command shell or a developer shell?
If it's a developer shell, which version of Visual Studio?

People make  lot of assumptions about each of our dev environments being the same. Getting these make and installs correct is really hard. It's often easier just to build fresh make files.

Also, I'm building x64 and the the freetype path implies it's intended for x86.

**Comment by jpbruyere** [comment]
FREETYPE_LIBRARY and CMAKE_TOOLCHAIN_FILE are cmake internal options that you may set on the command line with: ```cmake .. -DCMAKE_TOOLCHAIN_FILE=...```. You can also use cmake-gui command (cmake-gui ..).
FREETYPE_LIBRARY and FREETYPE_INCLUDE_DIRS should be automatically populated by cmake. The easyest way with cmake is the command line:
Note that the installed libraries path must be in your path to be found by cmake, here is a recap of the complete steps:
```
go to the root of your devel directory
git clone https://github.com/microsoft/vcpkg.git
cd vcpkg
bootstrap-vcpkg.bat
vcpkg install fontconfig freetype harfbuzz glfw3
vcpkg integrate install #not sure this is necessary
#add the installed shared libraries directory to your PATH environment variable
#something like 'vcpkg/installed/x64-windows/bin/'
cd .. #go up to your devel dir
git clone https://github.com/jpbruyere/vkvg.git --recursive
cd vkvg
mkdir build
cd build
cmake .. -DCMAKE_TOOLCHAIN_FILE=..\..\vcpkg\scripts\buildsystems\vcpkg.cmake
#now you must be able to to build the vcxproj in your build directory.
#if it complaints for missing shaders.h, recheck it from git, it's erased by the rebuildShaders target, but xxd executable is not found on windows, I have to debug that. (git checkout src/shaders.h)
```
I will try to complete the windows install tutorial with more detailed steps.

the visual studio command shell give you access to compilers with correct environment variables already set, maybe it's preferable.

**Comment by btipton-ds** [comment]
Ok, it's built.

These steps seem to be required. It would take a few cycles of deleting and rebuilding to prove it, best to assume they are.

vcpkg integrate install #not sure this is necessary
#add the installed shared libraries directory to your PATH environment variable
#something like 'vcpkg/installed/x64-windows/bin/'

When writing instructions, it's usually best to assume the worst in regard to the user's ability to understand them.

I recommend either adding 
"these instructions are a template or guide, they have not been tested on all systems."
or the the expensive process of testing them on all systems.

The huge variety of package managers and their details means that very few users will know all of them. I'd never seen vcpkg until this install.

To get x64 working I had to do this:
vcpkg install fontconfig:x64-windows freetype:x64-windows harfbuzz:x64-windows glfw3:x64-windows

I had to do it multiple times due to a spotty network connection (I'm working in the Philippines).

I had to wipe the cache because my first build was x86

vkvg\build>cmake .. -DCMAKE_TOOLCHAIN_FILE=..\..\vcpkg\scripts\buildsystems\vcpkg.cmake -G "Visual Studio 15 2017 Win64"

You can mark this one closed.

Thanks!
