### ISSUE TITLE
Examples fail creating the app

### ISSUE THREAD

**Issue by porky11** [jpbruyere/vkvg#43]
I get the following error message when trying to run one of the examples:
```
Fatal : VkResult is -6 in /home/porky11/build/vkvg/vkh/src/vkh_app.c at line 83
test_colinear: /home/porky11/build/vkvg/vkh/src/vkh_app.c:83: vkh_app_create: Assertion `res == VK_SUCCESS' failed.
```

**Comment by jpbruyere** [comment]
Are you building from source? if yes can you run it in Debug mode with validation enabled:
```
cmake .. -DCMAKE_BUILD_TYPE=Debug -DENABLE_VALIDATION=true
make
```
Are you able to run other examples?
Initialisation failed, so it's likely a vulkan environment configuration problem.
If you are using the vulkan sdk from lunarg, don't forget to set environment variables:
```
export VULKAN_SDK=/mnt/devel/vulkan/VulkanSDK/1.2.135.0/x86_64  <= change only here
export PATH=$VULKAN_SDK/bin:$PATH
export LD_LIBRARY_PATH=$VULKAN_SDK/lib
export VK_LAYER_PATH=$VULKAN_SDK/etc/vulkan/explicit_layer.d
```

**Comment by jpbruyere** [comment]
Also what's your operating system? linux or windows?

**Comment by porky11** [comment]
I build from source, current master

I tried your first tip, but it didn't work.

I get the same error for every example.

I don't have vulkan sdk installed. I just have the nvidia drivers and Vulkan-Headers from my repos installed and other libs using vulkan also work (for example the VulkanSamples).

I use linux, i.e. void linux, which is similar to arch linux, but has it's own package-manager

**Comment by jpbruyere** [comment]
can you give me the full output in debug mode with validation enabled?

**Comment by jpbruyere** [comment]
can you also give me the output of the command: 
```
vulkaninfo
```

**Comment by porky11** [comment]
Enabling validation didn't change anything first. I still had to install validation layers. And now most examples just work.

Did you try to run your program without validataion layers installed yet?

**Comment by porky11** [comment]
Besides, it even works without these options: `-DCMAKE_BUILD_TYPE=Debug -DENABLE_VALIDATION=true`

**Comment by jpbruyere** [comment]
In release mode, without validation or renderdoc enabled, it should work without layer installed.
What have you done to make it work? setting environment variables?

**Comment by porky11** [comment]
As said, I just installed Vulkan-ValidationLayers, which I didn't have installed before.
And also when specifying -DCMAKE_BUILD_TYPE=Release it also works without layers installed :)
