### ISSUE TITLE
Triangle Fan topology not supported on macOS

### ISSUE THREAD

**Issue by jpbruyere** [jpbruyere/vkvg#49]
Triangle fans are used to fill polygons with the Even/Odd technic, it's not supported by moltenVK.
A quick fix has be apply to disable Even/Odd on macOS.

The workaround is to bind the IBO in the _poly_fill() method and produce triangle list indices as the fan would output with the contour.

**Comment by fzwoch** [comment]
Just for the record, according to https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/chap21.html#drawing-primitive-topologies I understand it as that TRIANGLE_FAN is not part of the core and any implementation is free to not support it. With moltenVK probably being the most prominent.

> VK_PRIMITIVE_TOPOLOGY_TRIANGLE_FAN specifies a series of connected triangle primitives with all triangles sharing a common vertex. If the VK_KHR_portability_subset extension is enabled, and VkPhysicalDevicePortabilitySubsetFeaturesKHR::triangleFans is VK_FALSE, then triangle fans are not supported by the implementation, and VK_PRIMITIVE_TOPOLOGY_TRIANGLE_FAN must not be used.

**Comment by jpbruyere** [comment]
Should be ok with [bdd73c4].
