### ISSUE TITLE
pangocairo ➫ pangovkvg?

### ISSUE THREAD

**Issue by Rubo3** [jpbruyere/vkvg#66]
Would you like to be able to use Pango in concert with Vkvg, as you can do with Cairo in `pangocairo`? I could work on it.

**Comment by jpbruyere** [comment]
For sure, pango can do higher level shaping, this would be great.

**Comment by jpbruyere** [comment]
Note that I never used pango, even if I knew that it was able to output full text frame. Also Harfbuzz is part of vkvg core lib (optional).

**Comment by Rubo3** [comment]
We can use this issue to coordinate on the development of this integration.

**Comment by Rubo3** [comment]
I see many functions require [`cairo_font_type_t`](https://github.com/freedesktop/cairo/blob/a04786b9330109ce54bf7f65c7068281419cec6a/src/cairo.h#L1579), which can be one of `CAIRO_FONT_TYPE_TOY`, `CAIRO_FONT_TYPE_FT`, `CAIRO_FONT_TYPE_WIN32`, `CAIRO_FONT_TYPE_QUARTZ', `CAIRO_FONT_TYPE_USER`. What shall we implement? Also, Cairo has FreeType-specific headers and source files, should we do the same?

**Comment by jpbruyere** [comment]
That's a very good question. For now we have Freetype or stb_true_type as a compile option, this would be nice to implement also signed distance field font systems. For now vkvg does not discriminate font type, and I didn't felt the need to do so, maybe take some time on the question. I known that clear type native on win could achieve better polished output. Also freetype implementation in vkvg is quiet raw, cairo goes far more in details between options, I don't know if we should go that way, I want to keep things simple, having only font discimination between (bitmap, vector, sdf), not between font backends (quartz, win32, etc...)....

**Comment by jpbruyere** [comment]
Also cairo implemented win32 native fonts system surely to be able to compile without freetype on win platforms. We could have a native win32 font system implementation if as a compile option but I think it should be transparent for the api.

**Comment by Rubo3** [comment]
Since there are _a lot_ of things to implement, I thought it would be a good exercise to port the functions used by a program I am studying ([weston-editor](https://gitlab.freedesktop.org/wayland/weston/-/blob/main/clients/editor.c)): [`pango_cairo_create_layout`](https://gitlab.gnome.org/GNOME/pango/-/blob/main/pango/pangocairo-context.c#L480), [`pango_cairo_update_layout`](https://gitlab.gnome.org/GNOME/pango/-/blob/main/pango/pangocairo-context.c#L506) and [`pango_cairo_show_layout`](https://gitlab.gnome.org/GNOME/pango/-/blob/main/pango/pangocairo-render.c#L1133). Some functions which are currently missing from the Vkvg API can be easily reimplemented, but others need careful thought. Specifically, how should we implement [`_cairo_font_options`](https://github.com/freedesktop/cairo/blob/master/src/cairo-types-private.h#L190)? For example, does [`cairo_antialias_t`](https://github.com/freedesktop/cairo/blob/a04786b9330109ce54bf7f65c7068281419cec6a/src/cairo.h#L713) correspond to the `VkSampleCountFlags` passed to `vkvg_device_create`? Also, some functions need [`cairo_glyph_t`](https://github.com/freedesktop/cairo/blob/a04786b9330109ce54bf7f65c7068281419cec6a/src/cairo.h#L1115), which correspond to [`vkvg_glyph_info_t`](https://github.com/jpbruyere/vkvg/blob/5063f7049602437aa92abc773ac778b16a8d4207/src/vkvg_fonts.h#L151). Why did you choose to make it private? (Just asking, maybe it could be useful to make it public, maybe not)

**Comment by jpbruyere** [comment]
There, I made a conversion antialias->samplecount: https://github.com/jpbruyere/vgperf/blob/master/src/vkvg/common.c#L21
glyph_t has been quickly implemented to have stb_trutype implemented, we could think to make it public, but for harfbuzz, what overhead will it have...

**Comment by jpbruyere** [comment]
weston_editor is not really an editor, it's just some piece of code to output on single line of text as a sample app. I've made some complete editors, and I implemented in vkvg what I needed to replace cairo by vkvg in my apps: see https://github.com/jpbruyere/CrowEdit

**Comment by Rubo3** [comment]
> There, I made a conversion antialias->samplecount

Great, thanks!

> but for harfbuzz, what overhead will it have...

I'm sorry I'm not aware of this, what overhead will it have?

> weston_editor is not really an editor

That's true, but I am using it as an exercise to study Wayland, Cairo and Pango and as a base to make a text editor.

**Comment by Rubo3** [comment]
> There, I made a conversion antialias->samplecount

Compared with Cairo, I don't see equivalents (maybe I'm wrong or there are other ways to implement them) to `CAIRO_ANTIALIAS_GRAY`, `CAIRO_ANTIALIAS_SUBPIXEL`, the latter being related to another two components of [`_cairo_font_options`](https://github.com/freedesktop/cairo/blob/master/src/cairo-types-private.h#L190): [`cairo_subpixel_order_t`](https://github.com/freedesktop/cairo/blob/a04786b9330109ce54bf7f65c7068281419cec6a/src/cairo.h#L1315) and [`cairo_lcd_filter_t`](https://github.com/freedesktop/cairo/blob/a04786b9330109ce54bf7f65c7068281419cec6a/src/cairo-types-private.h#L182). For the moment we could set them to `*VKVG_*_NONE`, but should we implement them?

**Comment by jpbruyere** [comment]
developping pieces for each levels of the desktop graphic stack, gives a general idea of what's important, and helps to put at each levels good api's... vkvg has freetype lcd filter option as a compile option, but I have to double check it's not broken with all the recent changes. Selecting font filter is a global OS option in general...

**Comment by jpbruyere** [comment]
The most important task on the vkvg font system I see now is fully implementing harfbuzz text direction.

**Comment by Rubo3** [comment]
> developping pieces for each levels of the desktop graphic stack, gives a general idea of what's important, and helps to put at each levels good api's

So true. Then should we get rid of `cairo_lcd_filter_t`? What about `cairo_subpixel_order_t`?

**Comment by jpbruyere** [comment]
will lcd font filtering be still relevant with future harware....?

**Comment by Rubo3** [comment]
I guess the answer is no. I only recently started to learn these concepts, so I don't know much, that's why I ask silly questions, I'm sorry.

**Comment by jpbruyere** [comment]
Having lcd or not as a runtime option is not an easy task to implement in vkvg. lcd fonts are cached in rgb textures, non lcd are cached in single chanel textures. handling both as a runtime option is quiet some work to do....

**Comment by Rubo3** [comment]
Ok, thanks for the explanation. I'm removing them from `pangovkvg`. And what about [`cairo_hint_style_t`](https://github.com/freedesktop/cairo/blob/a04786b9330109ce54bf7f65c7068281419cec6a/src/cairo.h#L1347), [`cairo_hint_metrics_t`](https://github.com/freedesktop/cairo/blob/a04786b9330109ce54bf7f65c7068281419cec6a/src/cairo.h#L1368) and [`cairo_round_glyph_positions_t`](https://github.com/freedesktop/cairo/blob/a04786b9330109ce54bf7f65c7068281419cec6a/src/cairo-types-private.h#L188)? Are they needed in `vkvg`?

**Comment by jpbruyere** [comment]
this should be handled by harfbuzz I guess, there some discussions on hinting problems with latest pango-harfbuzz online....

**Comment by jpbruyere** [comment]
hinting should be internal anyway...

**Comment by Rubo3** [comment]
So `cairo_font_options_t` should be nuked.

**Comment by jpbruyere** [comment]
For now I don't see a good reason to implement further details of font option, but I'm working on multithreading, and I will maybe come back to this later....for now go along without....

**Comment by Rubo3** [comment]
Fine, thank you.

**Comment by Rubo3** [comment]
Hi, I updated the `pangovkvg` repo. Just an informative note: from the compiler warnings I see we currently miss some functions related to the scaled font and font options structs, which still need be removed and an alternative be found, then we miss font face creation and destruction, `vkvg_pattern_get_rgba`, `vkvg_user_to_device_distance`, and some functions related to text, `vkvg_text_path`, `vkvg_glyph_path`, `vkvg_show_text_glyphs`, `vkvg_show_glyphs`.

**Comment by Rubo3** [comment]
Actually, from the [docs](https://gitlab.freedesktop.org/cairo/cairo/-/blob/master/src/cairo.c#L3686), `cairo_show_text_glyphs` is an advanced version of `cairo_show_glyphs`, and if the target surface doesn't support it, it acts like `cairo_show_glyphs`.

**Comment by jpbruyere** [comment]
I don't known if the glyph based api really makes sense...

**Comment by Rubo3** [comment]
If the glyph API uselessly complicates vkvg, then it's "just" a matter of finding a way for Pango to render text without that API.

**Comment by jpbruyere** [comment]
If this api shows a real added value, than we can implement it...I guess it some kind of optimization for cairo lib,

**Comment by Rubo3** [comment]
It's hard to tell now, since at the moment I can't even get a trimmed down `pangovkvg` to compile...

**Comment by Rubo3** [comment]
It seems I don't get anymore warnings nor errors! It still doesn't compile though, I get undefined references on `pango_fc_font_map_*` functions, I updated the [readme](https://github.com/Rubo3/pangovkvg) with the steps to reproduce.

**Comment by Rubo3** [comment]
At long last, it compiles. Now I can test the features. I have added an example Makefile which takes care of the needed files and compiler flags.

**Comment by tmathews** [comment]
@Rubo3 does this repository still exist? I'm interested in using vkvg for my projects as a replacement for cairo and this would help me port over my existing code if it still works.

**Comment by jpbruyere** [comment]
Some notes worth reading...https://raphlinus.github.io/text/2022/11/08/minikin.html

**Comment by Rubo3** [comment]
@tmathews no, sorry, I have deleted it long ago and I don't have the code anymore. It did not work anyway.
