### ISSUE TITLE
Failed to compile because of missing function definitions

### ISSUE THREAD

**Issue by Rubo3** [jpbruyere/vkvg#71]
I pulled the recent changes from this repository and tried to build it, but the linkage failed:
```
[ 49%] Linking CXX executable arcs
/usr/bin/ld: CMakeFiles/tests_common.dir/common/vkengine.c.o: in function `vkengine_create':
[many undefined references]
/usr/bin/ld: ../libvkvg.a(vkvg_device.c.o): in function `vkvg_device_create':
[many undefined references]
collect2: error: ld returned 1 exit status
make[2]: *** [tests/CMakeFiles/arcs.dir/build.make:112: tests/arcs] Error 1
make[1]: *** [CMakeFiles/Makefile2:485: tests/CMakeFiles/arcs.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
```
I see some missing function definitions are related to `vkh_layer*` and `vkh_extension*`, have you perhaps forgotten to push changes to `vkhelpers`?

**Comment by jpbruyere** [comment]
have you update vkh submodule? I've made some changes on it, also you may enable cmake option `GIT_SUBMODULE` so that on each build the submodules are updated.

**Comment by Rubo3** [comment]
Oh, that's why: I built against `master`, not `devel`. I enabled `GIT_SUBMODULE` and it all went smoothly. Thanks!
