### ISSUE TITLE
Code formatting

### ISSUE THREAD

**Issue by Rubo3** [jpbruyere/vkvg#72]
Have you thought about using a code formatter like [astyle](http://astyle.sourceforge.net/) or [uncrustify](https://github.com/uncrustify/uncrustify)? It's good to have a consistent style.

**Comment by jpbruyere** [comment]
That you be great, I like to follow the same formatting rules.

**Comment by Rubo3** [comment]
Great! I was playing with `astyle`, it's dead easy to use, I ran:

```
astyle --style=google --attach-closing-while --indent-preproc-block --indent-preproc-define --indent-col1-comments --pad-oper --pad-comma --pad-header --unpad-paren --align-reference=name --break-one-line-headers --remove-braces --break-return-type --break-return-type-decl --convert-tabs --remove-comment-prefix --max-code-length=100 --break-after-logical < vkvg_context.c > vkvg_context_beautified.c
```
 
and this is the result: [vkvg_context_beautified.txt](https://github.com/jpbruyere/vkvg/files/7945908/vkvg_context_beautified.txt).
Not bad, but it could be better. On the other hand, `uncrustify` has _many_ more options, but the documentation is very minimal.
You can take some time to try some configurations and then decide which one you like more.

**Comment by jpbruyere** [comment]
clang-format file has been added in my current devel branch, will land in master soon.
