### ISSUE TITLE
text feature requests

### ISSUE THREAD

**Issue by billzez** [jpbruyere/vkvg#86]
Coming from nanovg, these are some features I miss:

1.  support for text strings that are not null terminated.  just a convenience for rendering long/multi-line text.
2.  load font from memory
3.  return array of glyph positions.  useful for selecting text with a mouse.
4.  font kerning without harfbuzz

**Comment by Rubo3** [comment]
> return array of glyph positions. useful for selecting text with a mouse.

I think that would be useful in pangovkvg, too.

**Comment by jpbruyere** [comment]
I've implemented your first point by adding vkvg_text_run_create2 with a length parameter (glyph count). ( #88 )
We should find a better name for the method, and also perform tests.

**Comment by Rubo3** [comment]
What about making `vkvg_text_run_create` a variadic function, with an optional `length` parameter, like the [`open`](https://www.man7.org/linux/man-pages/man2/open.2.html) system call? So you don't have to maintain two functions.

**Comment by Rubo3** [comment]
Or maybe just a non-variadic function, which always requires the `length` parameter, in which case a `strlen(text)` would suffice?

**Comment by jpbruyere** [comment]
> What about making `vkvg_text_run_create` a variadic function, with an optional `length` parameter, like the [`open`](https://www.man7.org/linux/man-pages/man2/open.2.html) system call? So you don't have to maintain two functions.

Bof, higher level wrappers may have problems to handle variadic func, and it add complexity to the code for a low gain.

**Comment by jpbruyere** [comment]
> Or maybe, to keep it simple, just a non-variadic function which always requires the `length` parameter, in which case for 0-terminated strings a `strlen(text)` would suffice?
harfbuzz compute length for null terminated string, also utf8 string is expected with the character count , not the byte length.

**Comment by Rubo3** [comment]
Oh ok

**Comment by billzez** [comment]
I like just calling it `vkvg_text_run_create_with_length`.

**Comment by jpbruyere** [comment]
>     1. support for text strings that are not null terminated.  just a convenience for rendering long/multi-line text.
So I've quickly implemented it, but not yet tested. 
>     2. load font from memory
For now, each font size has it's own face instance. I have to study this feature combined with 'single face shared among sizes', this is some work.
>     3. return array of glyph positions.  useful for selecting text with a mouse.
For harfbuzz, this is straightforward, I have to study how to do without.
>     4. font kerning without harfbuzz
I've never played with kerning by myself, maybe that's not too much work.

**Comment by billzez** [comment]
1.  Thank you.
2.  I think the easy thing would be to just store a pointer to the raw font data instead of the path in `vkvg_font_identity_t`, and then just skip the `fopen` (stbtt) or use `FT_New_Memory_Face`.
3.  I think this would just be a public API for `glyphs` in `vkvg_text_run_t`
4.  Freetype has `FT_Get_Kerning` and stbtt has `stbtt_GetGlyphKernAdvance`.

**Comment by jpbruyere** [comment]
>     2. I think the easy thing would be to just store a pointer to the raw font data instead of the path in `vkvg_font_identity_t`, and then just skip the `fopen` (stbtt) or use `FT_New_Memory_Face`.

This sounded a so good and straightforward idea that I've implemented it .    #89

**Comment by jpbruyere** [comment]
>     3. I think this would just be a public API for `glyphs` in `vkvg_text_run_t`
I've implemented vkvg_text_run_get_glyph_positions in the same branch, the struc returned will be different with hb or not, but it's a compile time feature...

**Comment by billzez** [comment]
> This sounded a so good and straightforward idea that I've implemented it . #89 I've quickly test it, tell me if it fits your needs.

Awesome.  I just checked, this is basically what nanovg does.  Although it only has one font struct.  It autoscales that font size with the transformation matrix.  This looks better better when zooming in, but probably uses a lot more memory.  The ideal solution is probably using mipmapping with the requested size and a set of arbitrarily chosen larger sizes scaled down.

**Comment by billzez** [comment]
> I've implemented vkvg_text_run_get_glyph_positions in the same branch, the struc returned will be different with hb or not, but it's a compile time feature...

Thanks.  It's unfortunate that `hb_glyph_position_t` is partially opaque with an undefined length.

One option is to define `vkvg_glyph_info_t` in the public API and internally just copy the 5 fields you need from `hb_glyph_position_t` over.

**Comment by jpbruyere** [comment]
Ah yes, an opaque pointer, so I would have had to implement some query functions on it. What about returning individual position elements by glyph index, I've pushed the fix.

**Comment by jpbruyere** [comment]
> > This sounded a so good and straightforward idea that I've implemented it . #89 I've quickly test it, tell me if it fits your needs.
> 
> Awesome. I just checked, this is basically what nanovg does. Although it only has one font struct. It autoscales that font size with the transformation matrix. This looks better better when zooming in, but probably uses a lot more memory. The ideal solution is probably using mipmapping with the requested size and a set of arbitrarily chosen larger sizes scaled down.

Due to font subpixel filtering, mipmapping could hardly improve. I plan to implement sdf fonts for adaptative scaling...

**Comment by jpbruyere** [comment]
vkvg don't use the freetype font matrix transform, cairo does, at least in some case. This transforms also the subpixel filter result (I need to double check, but if not, I can't see another advantage to have a font matrix), which gives better result. The vkvg's font cache store untransformed glyphs for each size. The context matrix transformation gives poor results on fonts due to the existing subpixel filter on cached glyphs.

**Comment by jpbruyere** [comment]
another option for better adaptative scaling, is uploading vectorized glyphs instead of rasterized bitmaps per sizes...

**Comment by billzez** [comment]
So rasterized for smaller sizes?  Yeah, that would probably be ideal.

**Comment by billzez** [comment]
stb fonts are not working because of this line:

```
assert(stbtt_InitFont(&font->stbInfo, font->fontBuffer, 0) && "stbtt_initFont failed");
```

assert() gets compiled out in release code, the font never gets initialized, and it segfaults.

**Comment by jpbruyere** [comment]
normally, the method should be called in release without the assert check. Do you experienced that the complete line is discarded? even the stbtt_InitFont call?

**Comment by billzez** [comment]
Correct, from assert.h:

```
ifdef NDEBUG
#define assert(x) (void)0
#else
#define assert(x) ((void)((x) || (__assert_fail(#x, __FILE__, __LINE__, __func__),0)))
#endif
```

**Comment by billzez** [comment]
In `_font_cache_create_text_run`, `strlen` still gets called on all strings.

**Comment by billzez** [comment]
I've confirmed the above fix works.

**Comment by Rubo3** [comment]
> return array of glyph positions. useful for selecting text with a mouse.

How would you implement text selection?
